
import { parseHtmlCityData } from './htmlParser';

interface CityFile {
  filename: string;
  componentName: string;
  routeName: string;
}

const cityFiles: CityFile[] = [
  { filename: 'aarhus.html', componentName: 'Aarhus', routeName: 'aarhus' },
  { filename: 'accra.html', componentName: 'Accra', routeName: 'accra' },
  { filename: 'addis-ababa.html', componentName: 'AddisAbaba', routeName: 'addis-ababa' },
  { filename: 'adelaide.html', componentName: 'Adelaide', routeName: 'adelaide' },
  { filename: 'ahmedabad.html', componentName: 'Ahmedabad', routeName: 'ahmedabad' },
  { filename: 'albuquerque.html', componentName: 'Albuquerque', routeName: 'albuquerque' },
  { filename: 'algiers.html', componentName: 'Algiers', routeName: 'algiers' },
  { filename: 'alice-springs.html', componentName: 'AliceSprings', routeName: 'alice-springs' },
  { filename: 'antwerp.html', componentName: 'Antwerp', routeName: 'antwerp' },
  { filename: 'arequipa.html', componentName: 'Arequipa', routeName: 'arequipa' },
  { filename: 'asuncin.html', componentName: 'Asuncion', routeName: 'asuncion' },
  { filename: 'auckland.html', componentName: 'Auckland', routeName: 'auckland' },
  { filename: 'austin.html', componentName: 'Austin', routeName: 'austin' },
  { filename: 'bandung.html', componentName: 'Bandung', routeName: 'bandung' },
  { filename: 'barranquilla.html', componentName: 'Barranquilla', routeName: 'barranquilla' },
  { filename: 'belgrade.html', componentName: 'Belgrade', routeName: 'belgrade' },
  { filename: 'belo-horizonte.html', componentName: 'BeloHorizonte', routeName: 'belo-horizonte' },
  { filename: 'bergen.html', componentName: 'Bergen', routeName: 'bergen' },
  { filename: 'bilbao.html', componentName: 'Bilbao', routeName: 'bilbao' },
  { filename: 'bologna.html', componentName: 'Bologna', routeName: 'bologna' },
  { filename: 'bordeaux.html', componentName: 'Bordeaux', routeName: 'bordeaux' },
  { filename: 'bratislava.html', componentName: 'Bratislava', routeName: 'bratislava' },
  { filename: 'brisbane.html', componentName: 'Brisbane', routeName: 'brisbane' },
  { filename: 'brno.html', componentName: 'Brno', routeName: 'brno' },
  { filename: 'broome.html', componentName: 'Broome', routeName: 'broome' },
  { filename: 'bucharest.html', componentName: 'Bucharest', routeName: 'bucharest' },
  { filename: 'busan.html', componentName: 'Busan', routeName: 'busan' },
  { filename: 'cairns.html', componentName: 'Cairns', routeName: 'cairns' },
  { filename: 'cairo.html', componentName: 'Cairo', routeName: 'cairo' },
  { filename: 'calgary.html', componentName: 'Calgary', routeName: 'calgary' },
  { filename: 'cali.html', componentName: 'Cali', routeName: 'cali' },
  { filename: 'cape-town.html', componentName: 'CapeTown', routeName: 'cape-town' },
  { filename: 'cartagena.html', componentName: 'Cartagena', routeName: 'cartagena' },
  { filename: 'casablanca.html', componentName: 'Casablanca', routeName: 'casablanca' },
  { filename: 'cebu.html', componentName: 'Cebu', routeName: 'cebu' },
  { filename: 'charleston.html', componentName: 'Charleston', routeName: 'charleston' },
  { filename: 'chiang-mai.html', componentName: 'ChiangMai', routeName: 'chiang-mai' },
  { filename: 'christchurch.html', componentName: 'Christchurch', routeName: 'christchurch' },
  { filename: 'colombo.html', componentName: 'Colombo', routeName: 'colombo' },
  { filename: 'columbus.html', componentName: 'Columbus', routeName: 'columbus' },
  { filename: 'copenhagen.html', componentName: 'Copenhagen', routeName: 'copenhagen' },
  { filename: 'crdoba.html', componentName: 'Cordoba', routeName: 'cordoba' },
  { filename: 'curitiba.html', componentName: 'Curitiba', routeName: 'curitiba' },
  { filename: 'cusco.html', componentName: 'Cusco', routeName: 'cusco' },
  { filename: 'da-nang.html', componentName: 'DaNang', routeName: 'da-nang' },
  { filename: 'dakar.html', componentName: 'Dakar', routeName: 'dakar' },
  { filename: 'dalat.html', componentName: 'Dalat', routeName: 'dalat' },
  { filename: 'dar-es-salaam.html', componentName: 'DarEsSalaam', routeName: 'dar-es-salaam' },
  { filename: 'darwin.html', componentName: 'Darwin', routeName: 'darwin' },
  { filename: 'debrecen.html', componentName: 'Debrecen', routeName: 'debrecen' },
  { filename: 'edmonton.html', componentName: 'Edmonton', routeName: 'edmonton' },
  { filename: 'fukuoka.html', componentName: 'Fukuoka', routeName: 'fukuoka' },
  { filename: 'gaborone.html', componentName: 'Gaborone', routeName: 'gaborone' },
  { filename: 'gdansk.html', componentName: 'Gdansk', routeName: 'gdansk' },
  { filename: 'genoa.html', componentName: 'Genoa', routeName: 'genoa' },
  { filename: 'ghent.html', componentName: 'Ghent', routeName: 'ghent' },
  { filename: 'gold-coast.html', componentName: 'GoldCoast', routeName: 'gold-coast' },
  { filename: 'gothenburg.html', componentName: 'Gothenburg', routeName: 'gothenburg' },
  { filename: 'guadalajara.html', componentName: 'Guadalajara', routeName: 'guadalajara' },
  { filename: 'guatemala-city.html', componentName: 'GuatemalaCity', routeName: 'guatemala-city' },
  { filename: 'guayaquil.html', componentName: 'Guayaquil', routeName: 'guayaquil' },
  { filename: 'halifax.html', componentName: 'Halifax', routeName: 'halifax' },
  { filename: 'hanoi.html', componentName: 'Hanoi', routeName: 'hanoi' },
  { filename: 'harare.html', componentName: 'Harare', routeName: 'harare' },
  { filename: 'havana.html', componentName: 'Havana', routeName: 'havana' },
  { filename: 'helsinki.html', componentName: 'Helsinki', routeName: 'helsinki' },
  { filename: 'hobart.html', componentName: 'Hobart', routeName: 'hobart' },
  { filename: 'hoi-an.html', componentName: 'HoiAn', routeName: 'hoi-an' },
  { filename: 'indianapolis.html', componentName: 'Indianapolis', routeName: 'indianapolis' },
  { filename: 'ipoh.html', componentName: 'Ipoh', routeName: 'ipoh' },
  { filename: 'jaipur.html', componentName: 'Jaipur', routeName: 'jaipur' },
  { filename: 'johannesburg.html', componentName: 'Johannesburg', routeName: 'johannesburg' },
  { filename: 'kampala.html', componentName: 'Kampala', routeName: 'kampala' },
  { filename: 'kansas-city.html', componentName: 'KansasCity', routeName: 'kansas-city' },
  { filename: 'kathmandu.html', componentName: 'Kathmandu', routeName: 'kathmandu' },
  { filename: 'kigali.html', componentName: 'Kigali', routeName: 'kigali' },
  { filename: 'kingston.html', componentName: 'Kingston', routeName: 'kingston' },
  { filename: 'krakow.html', componentName: 'Krakow', routeName: 'krakow' },
  { filename: 'la-paz.html', componentName: 'LaPaz', routeName: 'la-paz' },
  { filename: 'lagos.html', componentName: 'Lagos', routeName: 'lagos' },
  { filename: 'lahore.html', componentName: 'Lahore', routeName: 'lahore' },
  { filename: 'ljubljana.html', componentName: 'Ljubljana', routeName: 'ljubljana' },
  { filename: 'luanda.html', componentName: 'Luanda', routeName: 'luanda' },
  { filename: 'luang-prabang.html', componentName: 'LuangPrabang', routeName: 'luang-prabang' },
  { filename: 'lusaka.html', componentName: 'Lusaka', routeName: 'lusaka' },
  { filename: 'lyon.html', componentName: 'Lyon', routeName: 'lyon' },
  { filename: 'malacca.html', componentName: 'Malacca', routeName: 'malacca' },
  { filename: 'malaga.html', componentName: 'Malaga', routeName: 'malaga' },
  { filename: 'malm.html', componentName: 'Malmo', routeName: 'malmo' },
  { filename: 'manaus.html', componentName: 'Manaus', routeName: 'manaus' },
  { filename: 'maputo.html', componentName: 'Maputo', routeName: 'maputo' },
  { filename: 'maracaibo.html', componentName: 'Maracaibo', routeName: 'maracaibo' },
  { filename: 'marrakech.html', componentName: 'Marrakech', routeName: 'marrakech' },
  { filename: 'marseille.html', componentName: 'Marseille', routeName: 'marseille' },
  { filename: 'medellin.html', componentName: 'Medellin', routeName: 'medellin' },
  { filename: 'milwaukee.html', componentName: 'Milwaukee', routeName: 'milwaukee' },
  { filename: 'montevideo.html', componentName: 'Montevideo', routeName: 'montevideo' },
  { filename: 'nairobi.html', componentName: 'Nairobi', routeName: 'nairobi' },
  { filename: 'nashville.html', componentName: 'Nashville', routeName: 'nashville' },
  { filename: 'new-orleans.html', componentName: 'NewOrleans', routeName: 'new-orleans' },
  { filename: 'nice.html', componentName: 'Nice', routeName: 'nice' },
  { filename: 'nouma.html', componentName: 'Noumea', routeName: 'noumea' },
  { filename: 'oaxaca.html', componentName: 'Oaxaca', routeName: 'oaxaca' },
  { filename: 'oslo.html', componentName: 'Oslo', routeName: 'oslo' },
  { filename: 'ottawa.html', componentName: 'Ottawa', routeName: 'ottawa' },
  { filename: 'palermo.html', componentName: 'Palermo', routeName: 'palermo' },
  { filename: 'panama-city.html', componentName: 'PanamaCity', routeName: 'panama-city' },
  { filename: 'papeete.html', componentName: 'Papeete', routeName: 'papeete' },
  { filename: 'penang.html', componentName: 'Penang', routeName: 'penang' },
  { filename: 'perth.html', componentName: 'Perth', routeName: 'perth' },
  { filename: 'port-moresby.html', componentName: 'PortMoresby', routeName: 'port-moresby' },
  { filename: 'portland.html', componentName: 'Portland', routeName: 'portland' },
  { filename: 'porto.html', componentName: 'Porto', routeName: 'porto' },
  { filename: 'quebec-city.html', componentName: 'QuebecCity', routeName: 'quebec-city' },
  { filename: 'queenstown.html', componentName: 'Queenstown', routeName: 'queenstown' },
  { filename: 'quito.html', componentName: 'Quito', routeName: 'quito' },
  { filename: 'reykjavik.html', componentName: 'Reykjavik', routeName: 'reykjavik' },
  { filename: 'riga.html', componentName: 'Riga', routeName: 'riga' },
  { filename: 'rosario.html', componentName: 'Rosario', routeName: 'rosario' },
  { filename: 'sacramento.html', componentName: 'Sacramento', routeName: 'sacramento' },
  { filename: 'salt-lake-city.html', componentName: 'SaltLakeCity', routeName: 'salt-lake-city' },
  { filename: 'salvador.html', componentName: 'Salvador', routeName: 'salvador' },
  { filename: 'san-antonio.html', componentName: 'SanAntonio', routeName: 'san-antonio' },
  { filename: 'san-jose.html', componentName: 'SanJose', routeName: 'san-jose' },
  { filename: 'san-juan.html', componentName: 'SanJuan', routeName: 'san-juan' },
  { filename: 'savannah.html', componentName: 'Savannah', routeName: 'savannah' },
  { filename: 'seville.html', componentName: 'Seville', routeName: 'seville' },
  { filename: 'siem-reap.html', componentName: 'SiemReap', routeName: 'siem-reap' },
  { filename: 'sofia.html', componentName: 'Sofia', routeName: 'sofia' },
  { filename: 'stockholm.html', componentName: 'Stockholm', routeName: 'stockholm' },
  { filename: 'strasbourg.html', componentName: 'Strasbourg', routeName: 'strasbourg' },
  { filename: 'sucre.html', componentName: 'Sucre', routeName: 'sucre' },
  { filename: 'surabaya.html', componentName: 'Surabaya', routeName: 'surabaya' },
  { filename: 'suva.html', componentName: 'Suva', routeName: 'suva' },
  { filename: 'tallinn.html', componentName: 'Tallinn', routeName: 'tallinn' },
  { filename: 'tampere.html', componentName: 'Tampere', routeName: 'tampere' },
  { filename: 'the-hague.html', componentName: 'TheHague', routeName: 'the-hague' },
  { filename: 'thessaloniki.html', componentName: 'Thessaloniki', routeName: 'thessaloniki' },
  { filename: 'tunis.html', componentName: 'Tunis', routeName: 'tunis' },
  { filename: 'turin.html', componentName: 'Turin', routeName: 'turin' },
  { filename: 'utrecht.html', componentName: 'Utrecht', routeName: 'utrecht' },
  { filename: 'valencia.html', componentName: 'Valencia', routeName: 'valencia' },
  { filename: 'valparaiso.html', componentName: 'Valparaiso', routeName: 'valparaiso' },
  { filename: 'victoria.html', componentName: 'Victoria', routeName: 'victoria' },
  { filename: 'vilnius.html', componentName: 'Vilnius', routeName: 'vilnius' },
  { filename: 'warsaw.html', componentName: 'Warsaw', routeName: 'warsaw' },
  { filename: 'wellington.html', componentName: 'Wellington', routeName: 'wellington' },
  { filename: 'windhoek.html', componentName: 'Windhoek', routeName: 'windhoek' },
  { filename: 'winnipeg.html', componentName: 'Winnipeg', routeName: 'winnipeg' },
  { filename: 'yogyakarta.html', componentName: 'Yogyakarta', routeName: 'yogyakarta' },
  { filename: 'zagreb.html', componentName: 'Zagreb', routeName: 'zagreb' },
  { filename: 'zaragoza.html', componentName: 'Zaragoza', routeName: 'zaragoza' }
];

export async function convertHtmlToReact(htmlContent: string, componentName: string): Promise<string> {
  const cityData = parseHtmlCityData(htmlContent);
  
  return `import React from 'react';
import { CityPage } from '../../components/CityPage';

export const ${componentName}: React.FC = () => {
  return (
    <CityPage
      title="${cityData.title.replace(/"/g, '\\"')}"
      description="${cityData.description.replace(/"/g, '\\"')}"
      highlights={${JSON.stringify(cityData.highlights, null, 8)}}
      attractions={${JSON.stringify(cityData.attractions, null, 8)}}
      ${cityData.logistics ? `logistics={${JSON.stringify(cityData.logistics, null, 8)}}` : ''}
      ${cityData.faqs ? `faqs={${JSON.stringify(cityData.faqs, null, 8)}}` : ''}
    />
  );
};`;
}

export { cityFiles };
